<?php

namespace AppBundle\Repository;

/**
 * PlanetResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
